"""init usuarios

Revision ID: 2c5de5311bf9
Revises: daeda0d84f94
Create Date: 2025-05-15 23:01:12.945519

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '2c5de5311bf9'
down_revision: Union[str, None] = 'daeda0d84f94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
