"""Add unique constraint to Task model

Revision ID: 32ec036b232b
Revises: 3555dbe58d7b
Create Date: 2025-05-22 18:51:33.248591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32ec036b232b'
down_revision: Union[str, None] = '3555dbe58d7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('unique_user_task_title', 'task', ['user_id', 'titulo'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_user_task_title', table_name='task', postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###
