"""Add unique constraint to task

Revision ID: 3555dbe58d7b
Revises: 793252a7d909
Create Date: 2025-05-22 18:21:52.037392

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = '3555dbe58d7b'
down_revision: Union[str, None] = '793252a7d909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
