"""Add RecurrenceRule model

Revision ID: 3f641387ca16
Revises: 75cee56d2723
Create Date: 2026-09-28 12:31:54.968195

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3f641387ca16'
down_revision: str | None = '75cee56d2723'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurrencerule',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', name='recurrencefrequency'), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('next_due', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurrencerule_task_id'), 'recurrencerule', ['task_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recurrencerule_task_id'), table_name='recurrencerule')
    op.drop_table('recurrencerule')
    # ### end Alembic commands ###
