"""Add RoomMember and Task models

Revision ID: 75cee56d2723
Revises: f6c1d85f6e56
Create Date: 2026-09-26 02:00:28.198551

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '75cee56d2723'
down_revision: str | None = 'f6c1d85f6e56'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roommember',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('joined_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MEMBER', name='roommemberrole'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'room_id')
    )
    op.create_index(op.f('ix_room_owner_id'), 'room', ['owner_id'], unique=False)
    op.create_index(op.f('ix_room_parent_id'), 'room', ['parent_id'], unique=False)
    op.create_index(op.f('ix_tag_user_id'), 'tag', ['user_id'], unique=False)
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_recurring', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    op.create_index(op.f('ix_task_completed'), 'task', ['completed'], unique=False)
    op.create_index(op.f('ix_task_created_at'), 'task', ['created_at'], unique=False)
    op.create_index(op.f('ix_task_deleted_at'), 'task', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_task_room_id'), 'task', ['room_id'], unique=False)
    op.create_index(op.f('ix_task_user_id'), 'task', ['user_id'], unique=False)
    op.create_index(op.f('ix_taskassignment_asignado_por'), 'taskassignment', ['asignado_por'], unique=False)
    op.create_index(op.f('ix_taskassignment_fecha'), 'taskassignment', ['fecha'], unique=False)
    op.create_index(op.f('ix_taskassignment_task_id'), 'taskassignment', ['task_id'], unique=False)
    op.create_index(op.f('ix_taskassignment_user_id'), 'taskassignment', ['user_id'], unique=False)
    op.create_index(op.f('ix_taskhistory_task_id'), 'taskhistory', ['task_id'], unique=False)
    op.create_index(op.f('ix_taskhistory_timestamp'), 'taskhistory', ['timestamp'], unique=False)
    op.create_index(op.f('ix_taskhistory_user_id'), 'taskhistory', ['user_id'], unique=False)
    op.create_index(op.f('ix_tasktag_tag_id'), 'tasktag', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasktag_tag_id'), table_name='tasktag')
    op.drop_index(op.f('ix_taskhistory_user_id'), table_name='taskhistory')
    op.drop_index(op.f('ix_taskhistory_timestamp'), table_name='taskhistory')
    op.drop_index(op.f('ix_taskhistory_task_id'), table_name='taskhistory')
    op.drop_index(op.f('ix_taskassignment_user_id'), table_name='taskassignment')
    op.drop_index(op.f('ix_taskassignment_task_id'), table_name='taskassignment')
    op.drop_index(op.f('ix_taskassignment_fecha'), table_name='taskassignment')
    op.drop_index(op.f('ix_taskassignment_asignado_por'), table_name='taskassignment')
    op.drop_index(op.f('ix_task_user_id'), table_name='task')
    op.drop_index(op.f('ix_task_room_id'), table_name='task')
    op.drop_index(op.f('ix_task_deleted_at'), table_name='task')
    op.drop_index(op.f('ix_task_created_at'), table_name='task')
    op.drop_index(op.f('ix_task_completed'), table_name='task')
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('is_recurring')
    op.drop_index(op.f('ix_tag_user_id'), table_name='tag')
    op.drop_index(op.f('ix_room_parent_id'), table_name='room')
    op.drop_index(op.f('ix_room_owner_id'), table_name='room')
    op.drop_table('roommember')
    # ### end Alembic commands ###
