"""add nombre column to usuario

Revision ID: f6c1d85f6e56
Revises: 6926083f0630
Create Date: 2025-06-08 13:55:00.483791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel import sql


# revision identifiers, used by Alembic.
revision: str = 'f6c1d85f6e56'
down_revision: Union[str, None] = '6926083f0630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('nombre', sql.sqltypes.AutoString(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'nombre')
    # ### end Alembic commands ###
