"""Fix UUID TaskAssignment

Revision ID: f78ec3bfba5b
Revises: cddbdc0b939d
Create Date: 2025-05-23 02:43:29.950908

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'f78ec3bfba5b'
down_revision: str | None = 'cddbdc0b939d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
