"""add parent_id_and_room_id

Revision ID: fd7a1cfc7b9d
Revises: a132b4b95a59
Create Date: 2025-06-07 16:46:33.068422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd7a1cfc7b9d'
down_revision: Union[str, None] = 'a132b4b95a59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('parent_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'room', 'room', ['parent_id'], ['id'])
    op.add_column('task', sa.Column('room_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'task', 'room', ['room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'room_id')
    op.drop_constraint(None, 'room', type_='foreignkey')
    op.drop_column('room', 'parent_id')
    # ### end Alembic commands ###
